### ISSUE TITLE
Missing information due to cut off image.

### ISSUE THREAD

**Issue by Avialmonanay** [AdobeDocs/workfront-learn.en#2]
Issue in ./help/custom-data/calculated-expressions/get-started-with-calculated-fields-and-expressions.md

Issue page: https://experienceleague.adobe.com/docs/workfront-learn/tutorials-workfront/custom-data/calculated-expressions/get-started-with-calculated-fields-and-expressions.html?lang=en

Issue: The image to show all the different methods of the calculated expressions is cutoff at the "If" section and I believe is leaving the "IsBlank" completely off.

**Comment by betseyw15** [comment]
Hey there! I think this is regards to the last image on this page. The image is meant to just show some the expressions on the page but not all of them since there are dozens of expressions. So it only shows the top of the extensive list that can be found here: https://experienceleague.adobe.com/docs/workfront/using/reporting/reports/calculated-custom-data/calculated-data-expressions.html?lang=en

Hope that helps!
